sonar.organization=mp-david
sonar.projectKey=MP-David_sabor-local
sonar.projectName=sabor-local

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx
sonar.exclusions=src/**/*.test.js,src/**/*.test.jsx,src/test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.jsx,src/data/**,src/test/**
sonar.sourceEncoding=UTF-8
